### ISSUE TITLE
Error occurred in my performance monitor loop

### ISSUE THREAD

**Issue by apobekiaris** [gridsum/DataflowEx#19]
hi

Any ideas on what might cause such an exception?

> 18/01/05 00:05:44 [HttpClientFactory1] Error occurred in my performance monitor loop. Monitoring stopped. System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Common.Logging.Factory.AbstractLogger.StringFormatFormattedMessage.ToString() in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 164
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NLog.LogEventInfo.CalcFormattedMessage()
   at NLog.LogEventInfo..ctor(LogLevel level, String loggerName, IFormatProvider formatProvider, String message, Object[] parameters, Exception exception)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in C:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 949
   at Common.Logging.NLog.NLogLogger.DebugFormat(String format, Object[] args) in C:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 321
   at Gridsum.DataflowEx.Dataflow.<StartPerformanceMonitorAsync>d__34.MoveNext() in D:\eXpandFramework\Trading\DataflowEx-master\DataflowEx-master\Gridsum.DataflowEx\Dataflow.cs:line 328

**Comment by karldodd** [comment]
@apobekiaris Thanks for your report. 

This seems to be a simple bug/typo in line 328 of Dataflow.cs:

```C#
if (child.Completion.IsCompleted && verboseMode)
{
    LogHelper.PerfMon.DebugFormat("{0} is completed");
}
```

Will fix in the next minor version. For now, you can either fork and apply a hotfix yourself, or simply avoid using 'VerboseMode' for PerformanceLogMode.
